In [1]:
import numpy as np
import matplotlib.pyplot as plt
import variable as var
from disk import Disk
from chem import Chem
import matplotlib.pylab as pylab
import matplotlib.axes as ax


from scipy.stats import spearmanr
%matplotlib qt
dsk = Disk()
chm = Chem()
font = {'family' : 'normal',
        'weight' : 'bold',
        'size'   : 22}

pylab.rc('font', **font)

In [2]:
#functions:
def scatter(x,y,z,xlabel = '',ylabel='',clabel = '',title = ''):
    plt.figure(figsize=(15,8))
    plt.scatter(x,y,c=z, s = 10)
    plt.xlabel(xlabel, fontsize = 22,fontweight = 'bold')
    plt.ylabel(ylabel, fontsize = 22,fontweight = 'bold')
    plt.title(title)
    plt.colorbar(label = clabel)


def plot(x,y,xlabel = '',ylabel='',title = ''):
    plt.figure()
    plt.plot(x,y,'.')
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)


In [12]:
#Inputs:
name0 = 301

In [13]:
#Load data:
name_s = 'input/N_Atom.txt'
solar = np.loadtxt(name_s,dtype= str)[0:, 5].astype(float)

doc0 = 'Output/run_sum'+str(name0)+'.txt'
dat0 = np.loadtxt(doc0, dtype = str, skiprows = 1)[0:,1:].astype(float)

## Compare multiple data:

In [14]:
%matplotlib qt

P0 = dat0
plt.figure()
plt.plot(P0[:,7],P0[:,11]*solar[3]/(P0[:,13]*solar[5]),'.')

plt.xlabel('Metalicity')
plt.ylabel('C/O')
plt.show()

# Individual data:

In [15]:
#set the data you want to plot:
dat = dat0

In [16]:
#Plot regions:
%matplotlib qt

c = dsk.r_arr[4:]/var.au

gn = np.where((dat[:,11]*solar[3]/(dat[:,13]*solar[5]))<=0.92)
dat = np.copy(dat[gn])
g0 =np.where((dat[:,2]<=c[0]))
g1 =np.where((dat[:,2]<=c[1])&(dat[:,2]>c[0]))
g2 =np.where((dat[:,2]<=c[2])&(dat[:,2]>c[1]))
g3 =np.where((dat[:,2]<=c[3])&(dat[:,2]>c[2]))
g4 =np.where((dat[:,2]>c[3]))

datg0 = np.copy(dat[g0])
datg1 = np.copy(dat[g1])
datg2 = np.copy(dat[g2])
datg3 = np.copy(dat[g3])
datg4 = np.copy(dat[g4])

plt.figure()
plt.plot(datg4[:,7],datg4[:,11]*solar[3]/(datg4[:,13]*solar[5]),'g.',alpha = 0.75,label = 'Region 4')
plt.plot(datg3[:,7],datg3[:,11]*solar[3]/(datg3[:,13]*solar[5]),'b.',alpha = 0.75,label = 'Region 3')
plt.plot(datg2[:,7],datg2[:,11]*solar[3]/(datg2[:,13]*solar[5]),'r.',alpha = 0.75, label ='Region 2')
plt.plot(datg1[:,7],datg1[:,11]*solar[3]/(datg1[:,13]*solar[5]),'k.', label = 'Region 1')
plt.plot(datg0[:,7],datg0[:,11]*solar[3]/(datg0[:,13]*solar[5]),'.', color = 'cyan', label = 'Region 0')

plt.axhline(y=0.55,color='black')
plt.axvline(x=0.0,color='black')
plt.legend()
plt.xlabel('Metalicity', fontsize = 22,fontweight = 'bold')
plt.ylabel('C/O', fontsize = 22,fontweight = 'bold')
#plt.title('')
plt.show()
 

In [23]:
#Set the plot axis
data = dat
x = data[:,7]
y = data[:,11]*solar[3]/(data[:,13]*solar[5])
z1 = data[:,0]
z2 = data[:,2]
z3 = data[:,4]
z4 = data[:,5]


(array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
 <a list of 7 Text yticklabel objects>)

In [27]:
#Scatter plot based on distance
scatter(x,y,z2,'Metalicity','C/O','Orbital Distance')
plt.axhline(y=0.55,color='black')
plt.axvline(x=0.0,color='black')
plt.tick_params(size=5,width=2)
plt.xticks(fontsize=30)
plt.yticks(fontsize=30)
#plt.savefig('line_plot.pdf')

(array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
 <a list of 7 Text yticklabel objects>)

In [28]:
#Scatter plot based on mass
scatter(x,y,z1,'Metalicity','C/O','Initial Mass [M_E]')
plt.axhline(y=0.55,color='black')
plt.axvline(x=0.0,color='black')
plt.tick_params(size=5,width=2)
plt.xticks(fontsize=30)
plt.yticks(fontsize=30)

(array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
 <a list of 7 Text yticklabel objects>)

In [29]:
#Scatter plot based on dustgrains
scatter(x,y,z3,'Metalicity','C/O','dustgrain Ratio')
plt.axhline(y=0.55,color='black')
plt.axvline(x=0.0,color='black')
plt.tick_params(size=5,width=2)
plt.xticks(fontsize=30)
plt.yticks(fontsize=30)

(array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
 <a list of 7 Text yticklabel objects>)

In [30]:
#Scatter plot based on planetesimals
scatter(x,y,z4,'Metalicity','C/O','Planetesimal Ratio')
plt.axhline(y=0.55,color='black')
plt.axvline(x=0.0,color='black')
plt.tick_params(size=5,width=2)
plt.xticks(fontsize=30)
plt.yticks(fontsize=30)

(array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]),
 <a list of 7 Text yticklabel objects>)